version: 0.2
env:
  variables:
    S3_BUCKET: "codebuild-us-gov-west-1-206155274658-output-bucket"
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - ng build --prod
      - tar -cf dist.tar dist
      - ls -ltr
  
  post_build:
     commands:
      - aws s3 cp dist.tar s3://${S3_BUCKET} --recursive --include "*.tar"
      - echo Build completed on `date`
  
artifacts:
  files:
      - '**/*'
  base-directory: 'dist/*/*'
  discard-paths: yes