version: 0.2
env:
  variables:
    S3_BUCKET: "codebuild-us-gov-west-1-206155274658-output-bucket"
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - ng build --prod
      - mkdir distarch
      - cp -r scripts distarch
      - cp -r dist/*/** distarch
      - tar -cf distarch.tar distarch
      - tar rvf distarch.tar appspec.yml
      - cp distarch.tar dist

  post_build:
     commands:
      - aws s3 cp dist s3://${S3_BUCKET} --recursive --metadata '{"x-amz-meta-application-name":"AngularNew","x-amz-meta-deploymentgroup-name":"AngularEC2Deploy"}' --include "*.tar"
      - echo Build completed on `date`
  
artifacts:
  files:not
      - '**/*'
  base-directory: 'dist/*/*'
  discard-paths: yes